apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "do-database-metrics-adapter.fullname" . | quote }}
  labels:
    app: do-database-metrics-adapter
    component: database-metrics-adapter
    instance: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-database-metrics-adapter
      component: database-metrics-adapter
      instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: do-database-metrics-adapter
        component: database-metrics-adapter
        instance: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
          env:
            - name: DEBUG
              value: {{ .Values.settings.debug | quote }}
            - name: PORT
              value: {{ .Values.settings.port | quote }}
            - name: DO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "do-database-metrics-adapter.fullname" . | quote }}
                  key: do_token
            - name: DATABASE_NAME
              value: {{ .Values.settings.database_name | quote }}
