apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "do-database-metrics-adapter.fullname" . }}
  labels:
    app: do-database-metrics-adapter
    component: database-metrics-adapter
    instance: {{ .Release.Name | quote }}
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: do-database-metrics-adapter
      component: database-metrics-adapter
      instance: {{ .Release.Name | quote }}