apiVersion: v1
kind: Service
metadata:
  name: {{ include "do-database-metrics-adapter.fullname" . }}
  labels:
    app: do-database-metrics-adapter
    component: database-metrics-adapter
    instance: {{ .Release.Name | quote }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: do-database-metrics-adapter
    component: database-metrics-adapter
    instance: {{ .Release.Name | quote }}
